version: "3.8"

services:
  todo-app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
